server:
  port: 8080

spring:
  application:
    name: getchu
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME:900000}      # 15분
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:604800000} # 7일

lock:
  retry:
    max: 10
    initial-backoff-ms: 50
    max-backoff-ms: 1000
  expiration-seconds: 3