server:
  port: 8080

spring:
  application:
    name: getchu
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  # Refresh Token 미구현으로 인해 Access Token 만료시간을 24시간으로 설정
  # 추후 Refresh Token 도입 시 15분(900000ms)으로 단축 예정
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME:86400000}